=== Ivan-DonMoji/albares/hospital.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.example.com/hospital"
    xmlns="http://www.example.com/hospital"
    elementFormDefault="qualified">

    <xs:simpleType name="especialidad">
        <xs:restriction base="xs:string">
            <xs:enumeration value="trauma"></xs:enumeration>
            <xs:enumeration value="cardio"></xs:enumeration>
            <xs:enumeration value="neuro"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="hospital">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="profesionales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="auxiliares">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="auxiliar" minOccurs="0">
                                            <xs:complexType>
                                                <xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
                                                <xs:attribute name="nombre" type="xs:string"
                                                    use="optional"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cirujanos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cirujano">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:integer"></xs:element>
                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                    <xs:element name="apellidos" type="xs:string"
                                                        maxOccurs="2"></xs:element>
                                                    <xs:element name="seccion" type="xs:string"
                                                        maxOccurs="unbounded"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="enfermeros">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="enfermero" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                    <xs:element name="apellidos" type="xs:string"
                                                        maxOccurs="2"></xs:element>
                                                    <xs:element name="seccion" type="xs:string"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="doctores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="doctor" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:integer"></xs:element>
                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                    <xs:element name="apellidos" type="xs:string"
                                                        maxOccurs="2"></xs:element>
                                                    <xs:element name="seccion" type="xs:string"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="especialidad"
                                                    type="especialidad"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pacientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="paciente">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fichaMedica" type="xs:string"></xs:element>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="DNI" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ivan-DonMoji/albares/hospitalXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.example.com/hospital hospital.xsd"
          xmlns="http://www.example.com/hospital"
          nombre="Vegas">
    <profesionales>
        <auxiliares>
            <auxiliar id="1"/>
        </auxiliares>
        <cirujanos>
            <cirujano>
                <id>1</id>
                <nombre></nombre>
                <apellidos></apellidos>
                <seccion></seccion>
            </cirujano>
        </cirujanos>
        <enfermeros>
            <enfermero id="1">
                <nombre></nombre>
                <apellidos></apellidos>
                <seccion></seccion>
            </enfermero>
        </enfermeros>
        <doctores>
            <doctor especialidad="cardio">
                <id>1</id>
                <nombre></nombre>
                <apellidos></apellidos>
                <seccion></seccion>
            </doctor>
        </doctores>
    </profesionales>
    <pacientes>
        <paciente DNI="12345">
            <fichaMedica></fichaMedica>
            <nombre></nombre>
        </paciente>
    </pacientes>
</hospital>
